---
#
# Docker build for the Exam app backend
#

stages:
  - build
  - deploy

build_image:
  stage: build
  image: registry.duvall.org.uk/docker1/docker-in-docker:20.10.5-dind
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
      changes:
        - "*.go"
        - Dockerfile
    - when: never
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      docker build \
        --network host \
        -t "$CI_REGISTRY_IMAGE"":""$CI_BUILD_REF_SLUG" \
        -f Dockerfile \
        .
    - docker push "$CI_REGISTRY_IMAGE"":""$CI_BUILD_REF_SLUG"

deploy_container:
  stage: deploy
  image: registry.duvall.org.uk/docker1/alpine/runner:3.13.3
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
  script:
    - kubectl version
