apiVersion: v1
data:
  DB_USER: "{{ .Values.db.user | b64enc }}"
  DB_HOST: "{{ .Values.db.host | b64enc }}"
  DB_PORT: "{{ .Values.db.port | b64enc }}"
  DB_SCHEMA: "{{ .Values.db.schema | b64enc }}"
  DB_PASS: "{{ .Values.db.pass | b64enc }}"
kind: Secret
metadata:
  labels:
    k8s-app: exam-api
  name: api-db-config
  namespace: exam
type: Opaque
