apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: exam-api
  name: api
  namespace: exam
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: exam-api
  sessionAffinity: None
  type: ClusterIP
